# Configuration pour l'environnement Docker
spring:
  # Configuration de la base de données PostgreSQL
  datasource:
    url: jdbc:postgresql://postgres:5432/gescom
    username: ${SPRING_DATASOURCE_USERNAME:gescom_user}
    password: ${SPRING_DATASOURCE_PASSWORD:gescom_password}
    driver-class-name: org.postgresql.Driver
    
    # Configuration du pool de connexions HikariCP
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 600000
      connection-timeout: 20000

  # Configuration JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        
  # Configuration des sessions
  session:
    store-type: jdbc
    timeout: 30m
    
  # Configuration du cache
  cache:
    type: simple

# Configuration du serveur
server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Configuration des logs
logging:
  level:
    com.gescom: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/gescom.log
    max-size: 10MB
    max-history: 30

# Configuration des actionneurs Spring Boot
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
  health:
    db:
      enabled: true
    disk-space:
      enabled: true
      threshold: 1GB

# Configuration de sécurité
security:
  require-ssl: false

# Configuration personnalisée de l'application
app:
  # Configuration des uploads
  upload:
    max-file-size: 50MB
    max-request-size: 50MB
    path: /app/uploads
  
  # Configuration des emails (à adapter selon vos besoins)
  email:
    enabled: true
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    
  # Configuration des PDF
  pdf:
    enabled: true
    
  # Configuration de l'environnement
  environment: docker